version: '3.8'

services :
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: streaming
      POSTGRES_PASSWORD: streaming
      POSTGRES_DB: streaming
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8080
